### ISSUE TITLE
Is there a plan to provide a general zigma block implementation in the style of mambapy

### ISSUE THREAD

**Issue by ut21** [CompVis/zigma#13]
Basically a mamba model with zigzag scan but can be plugged into other models by taking in a tensor of shape B, L, D and returning output tensor of the same shape? Something like: [https://github.com/alxndrTL/mamba.py#usage](https://github.com/alxndrTL/mamba.py#usage)

**Comment by dongzhuoyao** [comment]
good proposal, I have put it in our plan.  We will notify you when we have those impl. Cheers~
