### ISSUE TITLE
But why do I set img_dim: to 32 and image_size to 256? AssertionError: Input height (42) doesn't match model (32). Isn't that the 32 pixels I'm expected to enter? Why did I change to 32 and expect me to enter 42?

### ISSUE THREAD

**Issue by xiaoxuesheng180** [CompVis/zigma#14]
Here is the code in my configuration file. Why does img_dim: set to 32 and image_size to 256 cause this problem? AssertionError: Input height (42) doesn't match model (32). Then I set img_dim: to 42 and image_size to 256, which results in an AssertionError: Input height (32) doesn't match model (42). What is the reason for this?The code's not working. Can you help me? Thank you so much!
train_steps: 10 #400_000
sample_vis_n: 1
video_frames: 0

batch_size: 1 #20
image_size: 256 #1024
num_classes: -1

target: model_zigma.ZigMa
params:
img_dim: 32
in_channels: 4
patch_size: 2
embed_dim: 768
depth: 24
scan_type: zigzagN8

**Comment by xiaoxuesheng180** [comment]
> Here is the code in my configuration file. Why does img_dim: set to 32 and image_size to 256 cause this problem? AssertionError: Input height (42) doesn't match model (32). Then I set img_dim: to 42 and image_size to 256, which results in an AssertionError: Input height (32) doesn't match model (42). What is the reason for this?The code's not working. Can you help me? Thank you so much! train_steps: 10 #400_000 sample_vis_n: 1 video_frames: 0
> 
> batch_size: 1 #20 image_size: 256 #1024 num_classes: -1
> 
> target: model_zigma.ZigMa params: img_dim: 32 in_channels: 4 patch_size: 2 embed_dim: 768 depth: 24 scan_type: zigzagN8

These are my run instructions：accelerate launch  --num_processes 1 --num_machines 1  --mixed_precision fp16    train_acc.py  model=s1024_zigzag8_b2_old  use_latent=0   data=facehq_1024  ckpt_every=10_000 data.sample_fid_n=5_000 data.sample_fid_bs=4 data.sample_fid_every=10_000  data.batch_size=1   note=_

**Comment by dongzhuoyao** [comment]
image_size: 256
img_dim: 32

image_size should alwasy be 8x of the img_dim, this is the requirement from the AutoEncoder.

**Comment by xiaoxuesheng180** [comment]
> image_size: 256 img_dim: 32
> 
> image_size should alwasy be 8x of the img_dim, this is the requirement from the AutoEncoder.

Yes, I set it like this: image_size: 256; img_dim: 32. But why is this a problem? AssertionError: Input height (42) doesn't match model (32). Is there something I'm not doing right? Thanks for answering!

**Comment by dongzhuoyao** [comment]
We follow previous works: LDM, please check taht paper for details:

https://github.com/CompVis/latent-diffusion

**Comment by xiaoxuesheng180** [comment]
> We follow previous works: LDM, please check taht paper for details:
> 
> https://github.com/CompVis/latent-diffusion

Thanks for your answer. I'll check it out
