### ISSUE TITLE
Scan Type Error: video_sst

### ISSUE THREAD

**Issue by kyle000603** [CompVis/zigma#15]
Hi, Thank you for your work.

I have an issue with the model **3d_zigzag8sst_b2**.
I have an error when copying and pasting your code that is

```
CUDA_VISIBLE_DEVICES="0,1,2,3" accelerate launch  --num_processes 4 --num_machines 1 --multi_gpu --mixed_precision fp16  --main_process_ip 127.0.0.1 --main_process_port 8868  train_acc.py  model=3d_zigzag8sst_b2  use_latent=1 data=ucf101  ckpt_every=10_000  data.sample_fid_n=20_0 data.sample_fid_bs=4 data.sample_fid_every=10_000  data.batch_size=4   note=_ 
```

And got an error raised

> Traceback (most recent call last):
>   File "/home/e1_u3/IRRLab/zigma/train_acc.py", line 198, in main
>     model, in_channels, input_size = get_model(args, device)
>                                      ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/e1_u3/IRRLab/zigma/utils/train_utils.py", line 54, in get_model
>     model = instantiate_from_config(args.model).to(device)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/e1_u3/IRRLab/zigma/utils/train_utils.py", line 37, in instantiate_from_config
>     instance = class_(**config.get("params", {}))
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/e1_u3/IRRLab/zigma/model_zigma.py", line 794, in __init__
>     raise ValueError("scan_type doesn't match")
> ValueError: scan_type doesn't match
> 

It seems to be caused from **scan_type: video_sst** in **3d_zigzag8sst_b2.yaml** at config/model/

Did I miss something?

**Comment by dongzhuoyao** [comment]
Hi, I have fixed the bug, please "git pull" to update the code
