### ISSUE TITLE
install error in 

### ISSUE THREAD

**Issue by huangjch526** [CompVis/zigma#17]
when: cd dis_causal_conv1d && pip install -e . && cd ..
error:
anaconda3/envs/zigma/compiler_compat/ld: cannot find -lgcc_s: No such file or directory
    collect2: error: ld returned 1 exit status
    
Can I skip this "cd dis_causal_conv1d && pip install -e . && cd .."? Since you ask me to "pip install causal_conv1d" already.

**Comment by dongzhuoyao** [comment]
Hi, can you search the related solution in https://github.com/state-spaces/mamba/issues ? hope it can help you
