### ISSUE TITLE
continuous scan

### ISSUE THREAD

**Issue by Beliefs666** [CompVis/zigma#24]
请问连续扫描的实现是哪一部分代码呢？

**Comment by dongzhuoyao** [comment]
具体看这里，我们先生成 scan path，然后再 rearrange，

https://github.com/CompVis/zigma/blob/f235fc801ec863aec895b42457d5e9e5e5c09d5c/utils/utils_zigzag.py#L333

**Comment by FeiSong123** [comment]
请问一下为什么print出来的结果是这样的
'''
[array([ 0,  1,  2,  3,  7,  6,  5,  4,  8,  9, 10, 11, 15, 14, 13, 12]), array([ 0,  4,  8, 12, 13,  9,  5,  1,  2,  6, 10, 14, 15, 11,  7,  3]), array([ 3,  2,  1,  0,  4,  5,  6,  7, 11, 10,  9,  8, 12, 13, 14, 15]), array([ 3,  7, 11, 15, 14, 10,  6,  2,  1,  5,  9, 13, 12,  8,  4,  0]), array([12, 13, 14, 15, 11, 10,  9,  8,  4,  5,  6,  7,  3,  2,  1,  0]), array([12,  8,  4,  0,  1,  5,  9, 13, 14, 10,  6,  2,  3,  7, 11, 15]), array([15, 14, 13, 12,  8,  9, 10, 11,  7,  6,  5,  4,  0,  1,  2,  3]), array([15, 11,  7,  3,  2,  6, 10, 14, 13,  9,  5,  1,  0,  4,  8, 12])]
'''

然后可视化结果是这样的，和论文里面的不符。以第一个为例[ 0,  1,  2,  3,  7,  6,  5,  4,  8,  9, 10, 11, 15, 14, 13, 12]，最后的终点不应该是15吗？
![image](https://github.com/user-attachments/assets/50e86c07-4447-4557-bffa-febf48e8e9d8)

**Comment by FeiSong123** [comment]
没事了`:joy:`，回头看几遍才发现是偶数行列的原因，没想到

**Comment by dongzhuoyao** [comment]
Thanks, i will close the issue, if you have other questions, feel free to reopen it.
