### ISSUE TITLE
code is error

### ISSUE THREAD

**Issue by Mr-Harry** [CompVis/zigma#7]
TypeError: Mamba.__init__() got an unexpected keyword argument 'scan_type'.

**Comment by 66ling66** [comment]
Did you solve this problem?

**Comment by dongzhuoyao** [comment]
Hi, could you tell me how to run into this error?

If you follow our installing tutorial, you should be able to run it successfully:

https://github.com/CompVis/zigma/blob/19ef944dd87673d258455d8f226a08ac8fa868ca/model_zigma.py#L1215
